// <auto-generated />
using GymRat.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GymRat.Migrations
{
    [DbContext(typeof(GymRatContext))]
    [Migration("20181119013902_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("GymRat.Models.GymItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BigPart");

                    b.Property<string>("Direction");

                    b.Property<string>("Height");

                    b.Property<string>("Name");

                    b.Property<string>("SmallPart");

                    b.Property<string>("Tags");

                    b.Property<string>("Uploaded");

                    b.Property<string>("Url");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.ToTable("GymItem");
                });
#pragma warning restore 612, 618
        }
    }
}
